package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ec.edu.sistemalicencias.dao.UsuarioDAO;
import ec.edu.sistemalicencias.model.entities.Usuario;
import ec.edu.sistemalicencias.model.exceptions.UsuarioException;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;

public class CrearUsuarioView {

    private JPanel panel1;
    private JLabel lblTitulo;
    private JTextField textUsuario;
    private JTextField txtRol;
    private JPasswordField passwordContrasenia;
    private JButton btnCrear;
    private JButton btnCancelar;
    private JLabel lblUsuario;
    private JLabel lblRol;
    private JLabel lblContrasenia;

    private UsuarioDAO usuarioDAO;

    public CrearUsuarioView(Connection conexion) {
        usuarioDAO = new UsuarioDAO(conexion);

        // Estilos
        panel1.setBackground(new Color(245, 245, 245));
        lblTitulo.setFont(new Font("Sans Serif", Font.BOLD, 18));
        btnCrear.setBackground(new Color(76, 175, 80));
        btnCrear.setForeground(Color.WHITE);
        btnCancelar.setBackground(new Color(189, 189, 189));
        btnCancelar.setForeground(Color.BLACK);

        // Botón Crear
        btnCrear.addActionListener(e -> crearUsuario());

        // Botón Cancelar
        btnCancelar.addActionListener(e -> SwingUtilities.getWindowAncestor(panel1).dispose());
    }

    //MÉTODO CREAR
    private void crearUsuario() {
        try {
            String usuario = textUsuario.getText().trim();
            String contrasenia = new String(passwordContrasenia.getPassword()).trim();
            String rol = txtRol.getText().trim();

            // Validaciones básicas
            validarCampos(usuario, contrasenia, rol);

            // Verificar si el usuario ya existe en la base de datos
            usuarioDAO.existeUsuario(usuario);

            // Crear usuario
            Usuario u = new Usuario(usuario, contrasenia, rol);
            usuarioDAO.crearUsuario(u);

            JOptionPane.showMessageDialog(panel1, "Usuario creado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();

        } catch (UsuarioException ex) {
            JOptionPane.showMessageDialog(panel1, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    //MÉTODOS AUXILIARES
    private void validarCampos(String usuario, String contrasenia, String rol) throws UsuarioException {
        if (usuario.isBlank()) throw new UsuarioException("El campo Usuario no puede estar vacío");
        if (usuario.length() < 4) throw new UsuarioException("Usuario debe tener al menos 4 caracteres");
        if (contrasenia.isBlank()) throw new UsuarioException("El campo Contraseña no puede estar vacío");
        if (contrasenia.length() < 6 || !tieneMayuscula(contrasenia) || !tieneMinuscula(contrasenia))
            throw new UsuarioException("Contraseña debe tener al menos 6 caracteres, incluyendo mayúscula y minúscula");
        if (!rol.equalsIgnoreCase("Administrador") && !rol.equalsIgnoreCase("Analista"))
            throw new UsuarioException("Rol inválido, debe ser Administrador o Analista");
    }

    private boolean tieneMayuscula(String str) {
        for (char c : str.toCharArray()) if (Character.isUpperCase(c)) return true;
        return false;
    }

    private boolean tieneMinuscula(String str) {
        for (char c : str.toCharArray()) if (Character.isLowerCase(c)) return true;
        return false;
    }

    private void limpiarCampos() {
        textUsuario.setText("");
        passwordContrasenia.setText("");
        txtRol.setText("");
    }

    public JPanel getPanel1() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblTitulo = new JLabel();
        lblTitulo.setText("FORMULARIO PARA CREAR EL USUARIO");
        panel2.add(lblTitulo, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblUsuario = new JLabel();
        lblUsuario.setText("Usuario");
        panel2.add(lblUsuario, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textUsuario = new JTextField();
        textUsuario.setText("");
        panel2.add(textUsuario, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtRol = new JTextField();
        txtRol.setText("");
        panel2.add(txtRol, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblContrasenia = new JLabel();
        lblContrasenia.setText("Contraseña: ");
        panel2.add(lblContrasenia, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordContrasenia = new JPasswordField();
        passwordContrasenia.setText("");
        panel2.add(passwordContrasenia, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblRol = new JLabel();
        lblRol.setText("Rol");
        panel2.add(lblRol, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnCrear = new JButton();
        btnCrear.setText("Crear");
        panel1.add(btnCrear, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}

