package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ec.edu.sistemalicencias.controller.UsuarioController;
import ec.edu.sistemalicencias.model.entities.Usuario;
import ec.edu.sistemalicencias.model.exceptions.UsuarioException;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;

public class LoginView {

    private JPanel panel1;
    private JLabel lblTitulo;
    private JLabel lblUsuario;
    private JLabel lblRol;
    private JTextField textUsuario;
    private JLabel lblContrasenia;
    private JPasswordField passwordContrasenia;
    private JComboBox<String> cbxRol;
    private JButton btnIniciarSesion;
    private JButton btnSalir;

    private final UsuarioController usuarioController;

    public LoginView(Connection conexion) {
        // Inicializar controller
        this.usuarioController = new UsuarioController(null);

        // Configuraciones de estilo
        panel1.setBackground(new Color(245, 246, 250));
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));

        // ====== ASIGNAR ACTION LISTENERS ======
        btnIniciarSesion.addActionListener(e -> iniciarSesion());
        btnSalir.addActionListener(e -> System.exit(0));
    }

    private void iniciarSesion() {
        try {
            String usuario = textUsuario.getText().trim();
            String contrasenia = new String(passwordContrasenia.getPassword()).trim();
            String rol = cbxRol.getSelectedItem().toString();

            if (usuario.isEmpty() || contrasenia.isEmpty()) {
                throw new UsuarioException("Complete todos los campos");
            }

            // Login devuelve el usuario
            Usuario usuarioLogueado = usuarioController.login(usuario, contrasenia, rol);

            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(panel1,
                    "Login exitoso\nRol: " + rol,
                    "Correcto",
                    JOptionPane.INFORMATION_MESSAGE);

            // Abrir MainView con el usuario logueado
            MainView mainView = new MainView(usuarioLogueado);
            mainView.setVisible(true);

            // Cerrar login
            cerrarVentana();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(panel1,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cerrarVentana() {
        Window w = SwingUtilities.getWindowAncestor(panel1);
        if (w != null) {
            w.dispose();
        }
    }

    public JPanel getPanel1() {
        return panel1;
    }

    // ===================== GUI DESIGNER =====================

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(7, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblTitulo = new JLabel();
        lblTitulo.setText("SISTEMA DE LICENCIAS ANT ");
        panel2.add(lblTitulo, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblUsuario = new JLabel();
        lblUsuario.setText("Usuario");
        panel2.add(lblUsuario, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textUsuario = new JTextField();
        textUsuario.setText("");
        panel2.add(textUsuario, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblContrasenia = new JLabel();
        lblContrasenia.setText("Contraseña: ");
        panel2.add(lblContrasenia, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordContrasenia = new JPasswordField();
        passwordContrasenia.setText("");
        panel2.add(passwordContrasenia, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblRol = new JLabel();
        lblRol.setText("Rol");
        panel2.add(lblRol, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbxRol = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Administrador");
        defaultComboBoxModel1.addElement("Analista");
        cbxRol.setModel(defaultComboBoxModel1);
        panel2.add(cbxRol, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel1.add(spacer3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnSalir = new JButton();
        btnSalir.setText("Salir ");
        panel1.add(btnSalir, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        panel1.add(spacer4, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnIniciarSesion = new JButton();
        btnIniciarSesion.setText("Iniciar Sesión");
        panel1.add(btnIniciarSesion, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}





